#!/usr/bin/with-contenv bash
# shellcheck shell=bash
exec s6-setuidgid abc /opt/ghidra-mcp/bin/python /opt/ghidra-mcp/run-bridge.py \
  --transport sse \
  --mcp-host 0.0.0.0 \
  --mcp-port 8081 \
  --ghidra-server http://127.0.0.1:8080/
